name: Deploy site from main folder to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main    # <-- 현재 사이트 파일이 들어있는 폴더
          publish_branch: gh-pages
          # optional: user name/email for commits
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com
